import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Testando c/ Vercel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <marquee scrollamount="6" behavior="alternate"><h1 className={styles.pb50}>Testando Vercel</h1></marquee>
        <div className={styles.description}>
          <p>
            Comando para criar app:&nbsp;
            <code className={styles.code}>npx create-next-app</code>
          </p>
          <div>
            <a
              href="https://github.com/mlsfront"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/mls.png"
                alt="Logo Git Hub"
                className={styles.vercelLogo}
                width={25}
                height={25}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/pomba.png"
            alt="Pomba Branca"
            width={600}
            height={600}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="github.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Git Hub <span>-&gt;</span>
            </h2>
            <p>Em suma, o GitHub é um serviço baseado em nuvem que hospeda um sistema de controle de versão (VCS) chamado&nbsp;Git.
            </p>
          </a>

          <a
            href="https://vercel.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Vercel <span>-&gt;</span>
            </h2>
            <p>
            A Vercel é uma plataforma voltada para a hospedagem de aplicações, é a criadora do framework Next JS,
            </p>
          </a>

          <a
            href="https://nextjs.org/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Next.js <span>-&gt;</span>
            </h2>
            <p>
            Next.js é um framework para React, uma biblioteca Javascript para construção de interfaces em cima do React.
            </p>
          </a>

          <a
            href="https://neon.tech/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Neon <span>-&gt;</span>
            </h2>
            <p>
            Neon permite que você ramifique instantaneamente seu banco de dados Postgres oferecendo suporte a fluxos de trabalho
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
